sudo: false
language: python
python: 2.7

before_install:
  - export GALAXY_REPO=https://github.com/galaxyproject/galaxy
  - export GALAXY_RELEASE=release_16.04
  - export CONDA_PREFIX="$HOME/conda"

install:
  - pip install -q flake8 planemo
  - planemo conda_init --conda_prefix "$CONDA_PREFIX"
  - export PATH="$CONDA_PREFIX/bin:$PATH"
  - conda create -y -q -c bioconda --name iuc_conda samtools=0.1.19 bcftools
  - . activate iuc_conda
  - planemo --version
  - conda --version
  - planemo shed_lint --report_level warn --tools --fail_level error --recursive .

script:
  - cd "$TRAVIS_BUILD_DIR" && flake8 -v --exclude=.git --ignore=E501 .
  - planemo conda_install --conda_ensure_channels r,bioconda,iuc --conda_prefix "$CONDA_PREFIX" .
  - planemo test --conda_dependency_resolution --conda_prefix "$CONDA_PREFIX" --galaxy_branch $GALAXY_RELEASE --galaxy_source $GALAXY_REPO .

after_failure:
  - cat tool_test_output.html | gzip | base64
